services:
  mongodb:
    image: mongo:7.0
    container_name: plt-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - plt-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: "0.5"

  backend:
    build:
      context: ./backend-plt-2
      dockerfile: Dockerfile.dev
    container_name: plt-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      BASE_URL: ${BASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    depends_on:
      - mongodb
    volumes:
      - ./backend-plt-2:/app
      - /app/node_modules
    networks:
      - plt-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: "0.5"

  frontend:
    build:
      context: ./frontend-plt
      dockerfile: Dockerfile.dev
    container_name: plt-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_VERCEL_BASE_URL: ${VITE_VERCEL_BASE_URL}
      VITE_VERCEL_SERVER_URL: ${VITE_VERCEL_SERVER_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend-plt:/app
      - /app/node_modules
    networks:
      - plt-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: "0.25"

volumes:
  mongodb_dev_data:
    driver: local

networks:
  plt-network:
    driver: bridge