check_db:
	chmod +x check_mongodb_local.sh
	./check_mongodb_local.sh
	
db_restart:
	sudo systemctl restart mongod

db_start:
	sudo systemctl start mongod

db_stop:
	sudo systemctl stop mongod

dev:
	sudo npm run dev