import { UnauthorizedException } from '@nestjs/common';

import { User } from '@/interfaces';
import { isValidEmail } from '@/utils';

export const validateFormRegistration = (body: any): User => {
  const { email, username, password, fullname, avatar } = body;

  const user: User = {
    id: '', // ID will be generated by the database
    email,
    username,
    password, // Password is required for registration
    fullname,
    avatar: avatar || '', // Optional avatar field
  };

  if (!user.email || !user.username || !user.password || !user.fullname) {
    throw new UnauthorizedException('miss_required_fields');
  }
  if (user.password.length < 6) {
    throw new UnauthorizedException('password_too_short');
  }
  if (!user.username.match(/^[a-zA-Z0-9_]+$/)) {
    throw new UnauthorizedException('username_invalid_format');
  }
  if (!isValidEmail(user.email)) {
    throw new UnauthorizedException('invalid_email_format');
  }
  if (!user.avatar) {
    throw new UnauthorizedException('avatar_required');
  }
  if (user.fullname.length < 3) {
    throw new UnauthorizedException('fullname_too_short');
  }

  return user;
}