dev:
	npm run start:dev

start:
	npm run start

build:
	npm run build

db_migrate_refresh:
	npm run db:reset

	npm run db:generate

	npm run db:migrate

	npm run db:push

	npm run db:seed

	rm -rf storages

prisma_studio:
	sudo npm run db:studio